name: Testing stuff

env:
  SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: skip in commit messages
        run: echo "$SKIP"

  inspect_vars:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: committer
        env:
          COMMITTER: ${{ toJson(github.actor) }}
        run: echo "$COMMITTER"
      - name: commit hash
        env:
          COMMIT_HASH: ${{ toJson(github.sha) }}
        run: echo "$COMMIT_HASH"
      - name: Define hostname env
        run: |
          echo "hostname=https://sample.com" >> "$GITHUB_ENV"
      - name: Print hostname
        run: |
          echo "${{ env.hostname }}" "${{ github.hostname }}"

  run_on_skip:
    if: ${{ env.SKIP == 'false' }}
    runs-on: ubuntu-20.04
    steps:
      - run: echo "if this is printed, then the if condition works"
